config/routes.rb
Rails.application.routes.draw do
  root "pokemons#index"
  resources :pokemons

  get "not_found", to: "pages#not_found"

  get "/pokedex", to: "pokedex#index"
  get "about", to: "pages#about"

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :pokemon_abilities
  has_many :pokemons, through: :pokemon_abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/generation.rb
class Generation < ApplicationRecord
  has_many :pokemons

  validates :g_name, :g_number, presence: true, uniqueness: true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  # Associations
  belongs_to :generation

  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_abilities
  has_many :abilities, through: :pokemon_abilities

  # Validations
  validates :name, presence: true
  validates :pokedex, presence: true, uniqueness: true
  validates :weight_kg, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validates :hp, :attack, :defense, :sp_attack, :sp_defense, :speed, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemon_types
  has_many :pokemons, through: :pokemon_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def not_found
  end
end

app/controllers/pokedex_controller.rb
class PokedexController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end
  def show
    @pokemon = Pokemon.find(params[:id])
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @types = Type.all
    @generations = Generation.all

    if params[:search].present?
      @pokemons = Pokemon.where("name LIKE ?", "%#{params[:search]}%").page(params[:page]).per(20)
      flash[:alert] = "No Pokémon found for your search." if @pokemons.empty?
    elsif params[:type_id].present?
      @pokemons = Pokemon.joins(:types).where(types: { id: params[:type_id] }).page(params[:page]).per(20)
    elsif params[:generation_id].present?
      @pokemons = Pokemon.where(generation_id: params[:generation_id]).page(params[:page]).per(20)
    else
      @pokemons = Pokemon.page(params[:page]).per(20)
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to not_found_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokedex_helper.rb
module PokedexHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pokedex" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/pb.png" type="image/png">
    <link rel="icon" href="/pb.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  </head>

  <body>
    <div class="container is-fullhd">
    <br>
    <nav class="navbar is-danger has-background-danger" role="navigation" aria-label="main navigation">
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to 'Home', pokemons_path, class: "navbar-item" %>
          <%= link_to 'Acerca de', about_path, class: "navbar-item" %>
        </div>
      </div>
    </nav>
    <br>

    <div class="is-flex is-justify-content-center">
      <figure class="image" style="width: 300px;">
        <img src="/pokedex.png" alt="Pokedex">
      </figure>
    </div>
    <%= yield %>
    </div>

    <footer class="footer has-background-dark has-text-white-ter" style="max-height: 100px;">
      <div class="content has-text-centered">
        <p>
          <strong class="has-text-danger">Pokedex Project</strong> developed by <a href="https://www.linkedin.com/in/anroman/" class="has-text-white">Andres Roman</a>
          // Rails Intro Project.
        </p>
        <p>
          <a href="https://github.com/a-roman222" class="has-text-white"><i class="fab fa-github"></i> &nbsp; GitHub</a>
        </p>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<section class="section">
        <div class="container">
            <h1 class="title has-text-centered">Pokedex Project</h1><br>
            <h2 class="subtitle has-text-centered">Explore Pokémon from Generations 1 to 7</h2>

            <div class="content">
                <p>This project is an interactive Pokedex that allows users to explore Pokémon from the first to the seventh generation, encompassing a total of approximately 800 Pokémon.</p>
                <p>The information for each Pokémon has been extracted from a CSV <a href="https://www.kaggle.com/datasets/rounakbanik/pokemon">(<i>kagle.com</i>)</a> database and organized into different tables for easier management and access.</p>
                <h3 class="subtitle">Database Model (ERD)</h3>
                <p>
                    <div class="has-text-centered" style="max-width: 700px;"><img src="/dbModel.png" alt=""></div>
                    <i><span>ERD tool:<a href="https://dbdiagram.io/"> dbdiagram.io</a></span></i>
                </p>

                <p>The Pokedex includes features such as:</p>
                <ul>
                    <li>Searching by name</li>
                    <li>Filtering by type and generation</li>
                    <li>Viewing individual details for each Pokémon</li>
                </ul>
                <p>Additionally, a modern design has been implemented using Bulma CSS, providing a user-friendly and visually appealing experience.</p>
                <p>This project is perfect for Pokémon enthusiasts and anyone looking to learn more about each creature and its characteristics.</p>
            </div>
        </div>
    </section>

app/views/pages/not_found.html.erb
<div class="container has-text-centered">
<br>
  <p class="subtitle">We're sorry, but the Pokemon you are looking for does not exist.</p>
  <img src="/404.png" alt="404" style="width: 350px;">
  <p>Please check the ID or try searching for a different Pokemon.</p><br>
  <%= link_to 'Back to Pokémons', pokemons_path, class: "button is-danger" %>
</div>
<br><br>

app/views/pokedex/index.html.erb
<h1>Pokedex#index</h1>

<table>
  <thead>
    <tr>
      <th>Pokedex</th>
      <th>Name</th>
      <th>Types</th>
      <th>Abilities</th>
      <th>Weight (kg)</th>
      <th>Legendary</th>
      <th>Generation</th>
    </tr>
  </thead>
  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.pokedex %></td>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.types.map(&:name).join(', ') %></td>
        <td><%= pokemon.abilities.map(&:name).join(', ') %></td>
        <td><%= pokemon.weight_kg %></td>
        <td><%= pokemon.is_legendary ? 'Yes' : 'No' %></td>
        <td><%= pokemon.generation&.g_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pokemons/index.html.erb
<%= form_with(url: pokemons_path, method: :get, local: true) do %>
  <div class="field is-grouped is-align-items-flex-end">
    <div class="control">
      <%= label_tag :search, "Search Pokémon by Name:", class: "label" %>
      <%= text_field_tag :search, params[:search], placeholder: "Enter Pokémon name", class: "input is-normal" %>
    </div>

    <div class="control">
      <%= label_tag :type_id, "Filter by Type:", class: "label" %>

      <div class="control">
        <div class="select">
          <%= select_tag :type_id, options_from_collection_for_select(@types.map { |type| [type.name.capitalize, type.id] }, :last, :first, params[:type_id]), include_blank: "All Types", class: "" %>
        </div>
      </div>
    </div>

    <div class="control">
      <%= label_tag :generation_id, "Generation:", class: "label" %>
      <div class="control">
        <div class="select">
          <%= select_tag :generation_id, options_from_collection_for_select(@generations, :id, :g_name, params[:generation_id]), include_blank: "All Generations", class: "" %>
        </div>
      </div>
    </div>

    <div class="control">
      <%= submit_tag "Search", class: "button is-primary has-background-danger" %>
    </div>
  </div>
<% end %>


<% if flash[:alert] %>
  <div class="alert alert-warning">
    <%= flash[:alert] %>
  </div>
<% end %>
<br>
<div class="table-container">
  <table class="table is-striped is-bordered is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Pokedex</th>
        <th>Name</th>
        <th>Weight (kg)</th>
        <th>Legendary</th>
        <th>Generation</th>
        <th>Types</th>
        <th>Abilities</th>
      </tr>
    </thead>
    <tbody>
      <% @pokemons.each do |pokemon| %>
        <tr>
          <td><%= pokemon.pokedex %></td>
          <td><%= link_to pokemon.name, pokemon_path(pokemon) %></td>
          <td><%= pokemon.weight_kg %></td>
          <td><%= pokemon.is_legendary ? 'Yes' : 'No' %></td>
          <td><%= pokemon.generation&.g_name %></td>
          <td><%= pokemon.types.map { |type| type.name.capitalize }.join(', ') %></td>
          <td><%= pokemon.abilities.map(&:name).join(', ') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


</div>
<div><%= paginate @pokemons %></div>
<br>

app/views/pokemons/show.html.erb
<div class="container">
  <h1 class="title has-text-centered"><%= @pokemon.name.capitalize %></h1>

  <div class="columns is-centered">
    <div class="column is-half" style="display: flex; flex-direction: column; align-items: center">
      <figure class="image " style="width: 200px; max">
        <img src="https://img.pokemondb.net/artwork/large/<%= @pokemon.name.downcase %>.jpg" alt="pokemon">
      </figure>
      <div class="box" style="min-width: 360px;">
        <table class="table is-striped is-hoverable is-fullwidth">

          <tbody>
            <tr>
              <td><strong>Pokedex:</strong></td>
              <td><%= @pokemon.pokedex %></td>
            </tr>
            <tr>
              <td><strong>Weight:</strong></td>
              <td><%= @pokemon.weight_kg %> kg</td>
            </tr>
            <tr>
              <td><strong>HP:</strong></td>
              <td><%= @pokemon.hp %></td>
            </tr>
            <tr>
              <td><strong>Attack:</strong></td>
              <td><%= @pokemon.attack %></td>
            </tr>
            <tr>
              <td><strong>Defense:</strong></td>
              <td><%= @pokemon.defense %></td>
            </tr>
            <tr>
              <td><strong>Special Attack:</strong></td>
              <td><%= @pokemon.sp_attack %></td>
            </tr>
            <tr>
              <td><strong>Special Defense:</strong></td>
              <td><%= @pokemon.sp_defense %></td>
            </tr>
            <tr>
              <td><strong>Speed:</strong></td>
              <td><%= @pokemon.speed %></td>
            </tr>
            <tr>
              <td><strong>Generation:</strong></td>
              <td><%= @pokemon.generation&.g_name %></td>
            </tr>
            <tr>
              <td><strong>Types:</strong></td>
              <td><%= @pokemon.types.map(&:name).join(', ').capitalize %></td>
            </tr>
            <tr>
              <td><strong>Abilities:</strong></td>
              <td><%= @pokemon.abilities.map(&:name).join(', ').capitalize %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="has-text-centered">
    <a class="button is-danger" href="<%= pokemons_path %>">Back to Pokedex</a>
  </div>
</div>
<br>